version: '1.0.{build}'
image: 
  - Ubuntu
services:
  - docker
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
build_script:
  - docker pull mcr.microsoft.com/mssql/server:2017-latest || true
  - docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=<YourStrong!Passw0rd>' -p 1433:1433 --name sql1 -d mcr.microsoft.com/mssql/server:2017-latest || true
  - docker exec -i sql1 /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P '<YourStrong!Passw0rd>' -Q 'ALTER LOGIN SA WITH PASSWORD="<YourNewStrong!Passw0rd>"' || true
  - dotnet ef database update --project source/Manga.Infrastructure --startup-project source/Manga.WebApi
  - dotnet build
  - pushd source/Manga.WebApi/
  - dotnet pack --configuration Release
  - popd
test_script:
  - dotnet test tests/Manga.UnitTests/Manga.UnitTests.csproj
  - dotnet test tests/Manga.IntegrationTests/Manga.IntegrationTests.csproj
  - dotnet test tests/Manga.AcceptanceTests/Manga.AcceptanceTests.csproj